### ISSUE TITLE
Version 2.0.1 throws a lot of errors

### ISSUE THREAD

**Issue by Geam** [CleyFaye/watchers#5]
I run in 2 separate bugs in version 2.0.1

- there are comments in `node_modules/.bin/watchers` (the license) that prevent the script from running
- there are some import from cjs modules which are not valid, exemple
```javascript
file:///home/user/myPackage/node_modules/@cley_faye/watchers/bin/watcher.js:28
import { OptionType } from "@cley_faye/loadconfig/lib/optiontype.js";
         ^^^^^^^^^^
SyntaxError: Named export 'OptionType' not found. The requested module '@cley_faye/loadconfig/lib/optiontype.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '@cley_faye/loadconfig/lib/optiontype.js';
const { OptionType } = pkg;
```

**Comment by CleyFaye** [comment]
Uh. Sounds like a problem.

**Comment by Geam** [comment]
for the usebanner, the src must be `["**/*.js", "!main.js"]`

**Comment by CleyFaye** [comment]
It also lacks a proper hashbang. It'll be fixed "soon" :D

**Comment by CleyFaye** [comment]
Might be fixed in fb024de7a49e0a219c2707af21b903f4c483cbb5 (v2.0.2)

**Comment by CleyFaye** [comment]
(hopefully)

**Comment by Geam** [comment]
Alright, I was doing something so I didn't test until now. I confirm that version 2.0.2 fixes the problems, I'm able to use watchers like expected. Thank you.
